### ISSUE TITLE
Getting started tutorial does not work on windows

### ISSUE THREAD

**Issue by Iqigai** [EbTech/EloR#12]
I have tried to run the example on windows 10 with gcc (installed with the code block IDE) and met several issues.
1. RUST_LOG error
When running from a dos window this command:
`\codeforces > RUST_LOG=debug cargo run --release --bin rate mmr codeforces`
it results in this error:
`The term 'RUST_LOG=debug' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.`

2. Compiling error, probably due to the file `quadmath.h` which seems missing.
If we somewhat run the other command without the RUST_LOG:
`\codeforces > cargo run --release --bin rate mmr codeforces`
We get an error, as well as a few warnings and a build fail:
`src/f128.c(2): fatal error C1083: Cannot open include file: 'quadmath.h': No such file or directory
  exit code: 2 ...`
`warning: build failed, waiting for other jobs to finish...`
The following warnings were emitted during compilation:
`warning: cl : Command line warning D9002 : ignoring unknown option '-Bstatic`
`warning: cl : Command line warning D9002 : ignoring unknown option '-lgfortran`
`warning: cl : Command line warning D9002 : ignoring unknown option '-lquadmath'`
`error: build failed`

**Comment by stephankokkas** [comment]
Same issue - I had it working but installed a new OS and now can't remember how I got it to work. Ive installed MSYS2 and MinGW, I've added cargo and gcc to variable path but still failed with 'f128_internal v0.2.2 with the same issues in your error (2)

```
warning: cl : Command line warning D9002 : ignoring unknown option '-Bstatic'
warning: cl : Command line warning D9002 : ignoring unknown option '-lgfortran'
warning: cl : Command line warning D9002 : ignoring unknown option '-lquadmath'
error: build failed
```

**Comment by Iqigai** [comment]
I have tried on mint linux as well as I had access to another computer but I got an error as well,  maybe that is related:

`error: could not compile 'proc-macro2' due to previous error
warning: build failed, waiting for other jobs to finish...`
`error: linking with `cc` failed: exit status: 1` 
and:
`note: /usr/bin/ld: cannot find Scrt1.o: No such file or directory`
`          /usr/bin/ld: cannot find crti.o: No such file or directory`
`          collect2: error: ld returned 1 exit status`

**Comment by EbTech** [comment]
Sorry for the delay. I removed the dependency on GCC's 128-bit floats, since experiments have determined the extra precision doesn't help. Do the other issues remain?

**Comment by EbTech** [comment]
@Iqigai RUST_LOG is an environment variable, and apparently those are set differently in Windows: https://stackoverflow.com/questions/18433840/logging-rust-programs
I'll have to update the documentation to reflect this...

**Comment by Iqigai** [comment]
> Sorry for the delay. I removed the dependency on GCC's 128-bit floats, since experiments have determined the extra precision doesn't help. Do the other issues remain?

I have tried again but I still get the same error. As a matter of fact I did clone the repos anew, but it seems that the default build is the same (it has the same size as the previous one). So unsurprisingly when I have tried to build I got the an error:
```
D:\Code\Elo-MMR-master\multi-skill>cargo run --release --bin rate mmr codeforces
   Compiling f128_internal v0.2.2
   Compiling serde v1.0.136
   Compiling tokio v1.16.1
   Compiling chrono v0.4.19
   Compiling tracing v0.1.30
   Compiling markup5ever v0.10.1
   Compiling statrs v0.13.0
   Compiling rayon v1.5.1
The following warnings were emitted during compilation:

warning: cl : Command line warning D9002 : ignoring unknown option '-Bstatic'
warning: cl : Command line warning D9002 : ignoring unknown option '-lgfortran'
warning: cl : Command line warning D9002 : ignoring unknown option '-lquadmath'

error: failed to run custom build command for `f128_internal v0.2.2`

Caused by:
  process didn't exit successfully: `D:\Code\Elo-MMR-master\target\release\build\f128_internal-02ef7bd0aedb50c0\build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-pc-windows-msvc")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_x86_64-pc-windows-msvc = None
  CC_x86_64_pc_windows_msvc = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-msvc = None
  CFLAGS_x86_64_pc_windows_msvc = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("false")
  running: "C:\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-W4" "-Bstatic" "-lgfortran" "-lquadmath" "-FoD:\\Code\\Elo-MMR-master\\target\\release\\build\\f128_internal-f4a14b8f27e43686\\out\\src/f128.o" "-c" "src/f128.c"
  cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-Bstatic'
  cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-lgfortran'
  cargo:warning=cl : Command line warning D9002 : ignoring unknown option '-lquadmath'
  f128.c
  src/f128.c(2): fatal error C1083: Cannot open include file: 'quadmath.h': No such file or directory
  exit code: 2

  --- stderr

  error occurred: Command "C:\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-W4" "-Bstatic" "-lgfortran" "-lquadmath" "-FoD:\\Code\\Elo-MMR-master\\target\\release\\build\\f128_internal-f4a14b8f27e43686\\out\\src/f128.o" "-c" "src/f128.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

warning: build failed, waiting for other jobs to finish...
The following warnings were emitted during compilation:

warning: cl : Command line warning D9002 : ignoring unknown option '-Bstatic'
warning: cl : Command line warning D9002 : ignoring unknown option '-lgfortran'
warning: cl : Command line warning D9002 : ignoring unknown option '-lquadmath'

error: build failed
```

**Comment by EbTech** [comment]
@Iqigai gosh that's surprising because not only `f128`, but your other dependencies (`tokio`, `statrs`) also refer to the versions used before the latest commit. Normally I'd suggest a `cargo clean`, but you already cloned anew hmmm

**Comment by Iqigai** [comment]
I did a `cargo clean` before launching the command and it worked. I think we can close this for now. As an FYI, there had been a few warnings during compilation and afterwards during the processing (I have sampled a couple at the bottom):

```
warning: unused import: `Float`
 --> multi-skill\src\systems\true_skill\normal.rs:1:26
  |
1 | use super::float::{erfc, Float, MyFloat, PI, TWO, ZERO};
  |                          ^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Float`
  --> multi-skill\src\systems\true_skill\mod.rs:10:13
   |
10 | use float::{Float, MyFloat, ZERO};
   |             ^^^^^

warning: field is never read: `old_rating`
  --> multi-skill\src\data_processing\cf_api.rs:25:5
   |
25 |     old_rating: i32,
   |     ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `new_rating`
  --> multi-skill\src\data_processing\cf_api.rs:26:5
   |
26 |     new_rating: i32,
   |     ^^^^^^^^^^^^^^^

warning: field is never read: `name`
   --> multi-skill\src\data_processing\cf_api.rs:161:5
    |
161 |     name: String,
    |     ^^^^^^^^^^^^

warning: field is never read: `duration_seconds`
   --> multi-skill\src\data_processing\cf_api.rs:163:5
    |
163 |     duration_seconds: u64,
    |     ^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `start_time_seconds`
   --> multi-skill\src\data_processing\cf_api.rs:164:5
    |
164 |     start_time_seconds: u64,
    |     ^^^^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `points`
  --> multi-skill\src\data_processing\ctf_api.rs:20:5
   |
20 |     points: String,
   |     ^^^^^^^^^^^^^^

warning: field is never read: `place`
  --> multi-skill\src\data_processing\ctf_api.rs:21:5
   |
21 |     place: usize,
   |     ^^^^^^^^^^^^

warning: field is never read: `limit`
  --> multi-skill\src\data_processing\ctf_api.rs:27:5
   |
27 |     limit: usize,
   |     ^^^^^^^^^^^^

warning: field is never read: `offset`
  --> multi-skill\src\data_processing\ctf_api.rs:29:5
   |
29 |     offset: usize,
   |     ^^^^^^^^^^^^^

warning: field is never read: `aliases`
  --> multi-skill\src\data_processing\ctf_api.rs:35:5
   |
35 |     aliases: Vec<String>,
   |     ^^^^^^^^^^^^^^^^^^^^

warning: field is never read: `country`
  --> multi-skill\src\data_processing\ctf_api.rs:36:5
   |
36 |     country: String,
   |     ^^^^^^^^^^^^^^^

warning: field is never read: `academic`
  --> multi-skill\src\data_processing\ctf_api.rs:37:5
   |
37 |     academic: bool,
   |     ^^^^^^^^^^^^^^

...
2022-03-15T10:05:10.743350Z  WARN multi_skill::systems::elo_mmr: Subsampling 12458 opponents might be slow; consider decreasing subsample_size.

2022-03-15T10:08:52.278564Z  WARN multi_skill::systems::elo_mmr: Subsampling 14213 opponents might be slow; consider decreasing subsample_size.
```

**Comment by EbTech** [comment]
Oh yeah I know about the warnings thanks, I hope to clean them up someday. Glad it's working now!
