### ISSUE TITLE
Rating decay

### ISSUE THREAD

**Issue by Wulfheart** [EbTech/EloR#13]
Hello,

I am not sure if I understood the implementation/paper correctly. I want a players rating to decay over time so that a player who hasn't been active for a long while isn't ranked as high as an active player. Is there any way to achieve this?

**Comment by EbTech** [comment]
Yes! The `drift_per_sec` parameter increases a player's `sigma^2` by the specified amount per second. If a player's rating is then reported as the lower confidence bound `mu - 3*sigma` (similar to TrueSkill), inactive players will be reported to have a lower rating.

**Comment by Wulfheart** [comment]
Thank you for your reply! I really appreciate it. 

This is awesome!
