### ISSUE TITLE
Possible logical error

### ISSUE THREAD

**Issue by duhby** [EbTech/EloR#21]
https://github.com/EbTech/Elo-MMR/blob/05a7e0085b3114a5bf56e8824635b11c2ab6eda4/multi-skill/src/systems/elo_mmr.rs#L257

To my understanding, Player.update_time is the time (in seconds) that the current competition we're rating for took place since the epoch, and Player.delta_time is the time in seconds between the current competition and the last competition that the player played in.

So, correct me if I'm wrong, but shouldn't this reference player.delta_time instead of player.update_time? Looking through the code, I didn't see a single place where player.delta_time was used for something, so I thought it might be here. If I'm wrong, then is there some place else in the code that uses it that I'm missing?

**Comment by EbTech** [comment]
Oops, I think you're right. Time decay is an extra feature that's off by default, so the bug wouldn't have appeared in our use cases...

**Comment by EbTech** [comment]
Done, Thanks!
