### ISSUE TITLE
How to determine rating after each competiton?

### ISSUE THREAD

**Issue by atiabjobayer** [EbTech/EloR#8]
I saw that after calculating rating, we get a csv for each player. That these contains these fields "contest_index,rating_mu,rating_sig,perf_score,place"

How can I determine that player's rating change after each game from those fields? Please help.

**Comment by stephankokkas** [comment]
You can match the contest_index with the .json file which you created for each match. The order is most recent at the top to least recent at the bottom.

**Comment by EbTech** [comment]
@stephankokkas Thanks for the help :) yep info about all matches is in `all_contests.csv`
@atiabjobayer If you just want the rating changes, is there anything more to do than subtract the `rating_mu` (or if you prefer, `rating_mu - 2*rating_sig`) between adjacent rows? There's even [code for reading CSVs](https://github.com/EbTech/Elo-MMR/blob/fd3cf25ee9b75937279e804451cf8bc05294e197/worldrank-api/src/immut_database.rs#L10).
